### ISSUE TITLE
Very long lines

### ISSUE THREAD

**Issue by AugustT** [ourcodingclub/CC3-DataManip#1]
https://github.com/ourcodingclub/CC-3-DataManip/blob/e23e663077f8b48f3161c8e557a147e73c7cc55d/CC_SAB_tidyr_piping.R#L41

Some of the lines in this tutorial (and maybe others) are VERY long which makes them hard to read in Rstudio. Break these up to make things easier.

**Comment by AugustT** [comment]
@gndaskalova did you see this issue? not sure if it i the best way to give you feedback?

**Comment by gndaskalova** [comment]
Ah, thanks for the email, for some reason the Issues tab had disappeared, but I brought it back and now I can see it! That is a totally fair point, I will go make those edits now, I really don't like having to scroll back and forth, so thanks for pointing that out!

**Comment by AugustT** [comment]
Are you happy for me to use the issues tabs on these repos to report feedback?

**Comment by gndaskalova** [comment]
Yes, that would be great, now that I have re-discovered it, I'll be more on it. If it's a quick fix on something, you could also fork the repo, make changes and then do a pull request, but I'm happy with either.
